name: Cloudflare Pages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.120.0"
          extended: true
      - run: cd biosugar0 && hugo --gc --minify
        env:
          HUGO_VERSION: "0.120.4"
          HUGO_ENV: "production"
          HUGO_ENABLEGITINFO: "true"
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "biosugar0-com"
          directory: "biosugar0/public"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
